### ISSUE TITLE
Installing Leap Motion Plugin Breaks Install

### ISSUE THREAD

**Issue by ajayyy** [AndersMalmgren/FreePIE#101]
After installing the leap motion plugin, my install has broken, and it will not open, even on older versions. Here is the log:

> 1/16/2017 5:01:50 PM - System.NotSupportedException - An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.: 
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at FreePIE.Core.Plugins.PluginInvoker.ListAllPluginTypes()
>    at FreePIE.Core.Plugins.PluginInvoker.PopulatePluginSettings()
>    at FreePIE.Core.Persistence.PersistanceManager.Load()
>    at FreePIE.GUI.Bootstrap.BootStrapper.OnStartup(Object sender, StartupEventArgs e)
>    at System.Windows.Application.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I have been told by [this](https://www.reddit.com/r/vridge/comments/5o1hk1/wiimote_leap_motion_controls_freepie_plugin/dcirc70/) person that this is unfix able. If this is true, this definitely should be fixed in FreePIE  itself.

**Comment by ajayyy** [comment]
Found a solution:

http://stackoverflow.com/questions/15238714/net-local-assembly-load-failed-with-cas-policy

The plugin files are marked as unsafe...

**Comment by AndersMalmgren** [comment]
ah, yeah, a classic problem.
