### ISSUE TITLE
multiply saitek x52 rudder values, can it be done?

### ISSUE THREAD

**Issue by MigLeader** [AndersMalmgren/FreePIE#102]
i got a bad rudder potentiometer on my x52 , i replaced it with another one but it have less value , can i use FreePIE to override these values.

for example now it just moves about 1/3 of the whole range , lets assume the range is from 0-100 now it just moves to 33 only.

if yes its possible , i wish its not rude to ask this, but can someone post the code for doing so.

thanks for any help i get.

**Comment by AndersMalmgren** [comment]
Hi, it could be done with vjoy i guess. Read the value from the real saitek, retarget the range using filter.maprange and output on vjoy. Problem is we can not hide the real joysticks values to games so I hope the game will ignore the real stick if you configure it to use the vjoy stick

**Comment by MigLeader** [comment]
hello , thanks for respond , i was lucky and it worked with me, here i used this script:

```
from System import Int16

if starting:
   joystick[0].setRange(0, 2000)
   
z = joystick[0].zRotation

vJoy[0].z = filters.mapRange(z, 0, 2000, -Int16.MaxValue, Int16.MaxValue)

diagnostics.watch(z)
diagnostics.watch(vJoy[0].z)
```

and i go to elite dangerous , and reassign the controls but moving the stick to the right , don't know why but to the left detects the original stick but to the right detects vjoy stick , so just i moved the stick to the right and it works for me.

**Comment by AndersMalmgren** [comment]
Glad it worked for you!
