### ISSUE TITLE
Freepie Crashing on Startup

### ISSUE THREAD

**Issue by GoDzViper** [AndersMalmgren/FreePIE#113]
As the title says freepie is crashing on startup. I have tried uninstalling and then reinstalling the program multiple times, tried running in compatibility mode for multiple versions of windows includinf: Windows 8, Windows 7 and Windows Vista. I am currently using windows 10 64x.

**Comment by MarijnS95** [comment]
If there is an error message, can you share it? Same for the log file in the installation directory.

Otherwise, do you have plugins? Those usually have the "downloaded from the internet" flag enabled, preventing freepie from starting up (the starting procedure silently fails whilst the process keeps running, without a window showing up).

**Comment by GoDzViper** [comment]
No error message just the normal "FreePIE.GUI has stopped working" message that pops up when a program crashes. I'm assuming the log file would be a text document directly in the freepie root directory correct? If so there isn't a log file to send. 

The only thing in the plugins folder is "FreePIE.Core.Plugins.dll" which I'm assuming is supposed to be in there but I'm not too sure. FreePIE does fully close and isn't running in the background after crashing.

**Comment by AndersMalmgren** [comment]
The log file is in %appdata%/freepie

**Comment by GoDzViper** [comment]
Ok cool found it :D Added it to pastebin so that i didnt flood the comment with the log. https://pastebin.com/ai0LA9EV

**Comment by AndersMalmgren** [comment]
Try deleting layout.config could be invalid data in it causing this.

**Comment by GoDzViper** [comment]
Awesome must have been invalid data then. Deleted the layout.cofig and it launched perfectly!! Thanks for the help.

**Comment by AndersMalmgren** [comment]
cool, will see if there are new versions of the docking library
