### ISSUE TITLE
GUI does not show up

### ISSUE THREAD

**Issue by belger-dussen** [AndersMalmgren/FreePIE#162]
When I start FreePIE it does not show anything, no GUI. However, I do see process on task manager (FREEPIE.GUI). 
How can I fix this problem?

**Comment by belger-dussen** [comment]
I was able to work around by installing into user directory, not to Program Files.

**Comment by AndersMalmgren** [comment]
Strange, shouldnt be a issue, anthing in the log or windows event viewer?

**Comment by belger-dussen** [comment]
Thanks for your reply.
Actually I found that one of the plugins was doing bad. It was not about the installation. 
The plugin I was using was stopped by Windows Defender Smartscreen and as soon as I gave permission to run, FreePie did launch properly.
