### ISSUE TITLE
SetPressed won´t reset on Midi Endless Rotary

### ISSUE THREAD

**Issue by vinKaiZen** [AndersMalmgren/FreePIE#167]
Good afternoon,

i´ve got a problem which i can´t solve. I use a Traktor X1 Midi Controller and want to use it as virtual joystick in my sim to change heading, altitude with the endless rotary encoder as in real life.

Inside the NI Controller Editor i changed the endless rotary encoder to send notes in booth directions
my actual code works in booth directions but the vjoy button will be still pressed hole time until i change to the opposite direction. I don´t unterstand this because it´s a setPressed command.
I need a code change to manually "Zero" the Status of the Buttons 37 & 38 after it gets activated

Actual Code:
```def update():
   diagnostics.watch(midi[0].data.channel)
   diagnostics.watch(midi[0].data.status)
   diagnostics.watch(midi[0].data.buffer[0])
   diagnostics.watch(midi[0].data.buffer[1])


   #Rotary LEFT
if midi[0].data.buffer[0] == 2: 
	vJoy[0].setPressed(37)

   #Rotary RIGHT
if midi[0].data.buffer[0] == 3: 
	vJoy[0].setPressed(38)

if starting:
	midi[0].update += update```

**Comment by MarijnS95** [comment]
@vinKaiZen Could you edit your post with the script in a code block (using backticks, see https://help.github.com/articles/creating-and-highlighting-code-blocks/)? That way indentation is preserved, which is essential for Python and thus for us to see whether the script is correct.

I guess this should be it, right?
```python
def update():
    diagnostics.watch(midi[0].data.channel)
    diagnostics.watch(midi[0].data.status)
    diagnostics.watch(midi[0].data.buffer[0])
    diagnostics.watch(midi[0].data.buffer[1])

    #Rotary LEFT
    if midi[0].data.buffer[0] == 2:
        vJoy[0].setPressed(37)
    
    #Rotary RIGHT
    if midi[0].data.buffer[0] == 3:
        vJoy[0].setPressed(38)

if starting:
    midi[0].update += update
```

Other than that, I do not see anything wrong. As long as there's no other part of the script that blocks on something indefinitely, the pressed strategy should be updated for every iteration. As a temporary alternative you could try setting the pressed state to `False` at the beginning of the script, and enable it in update with `vJoy[0].setPressed(37, midi[0].data.buffer[0] == 2)`; since the script is executed for every update iteration, this should turn the button on until the next script iteration just like `setPressed` without state would do.

**Comment by AndersMalmgren** [comment]
the tickrate could also be too fast for the driver or game to register. Someone with enough time on their hand should rewrite the ```SetPressedStrategy``` so it uses a ```StopWatch``` instead and wait with the reset until a certain amount of time have passed. Something like this, NOT TESTED!!!

```
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace FreePIE.Core.Plugins.Strategies
{
    public class SetPressedStrategy<TKey>
    {
        private readonly Action<TKey> onPress;
        private readonly Action<TKey> onRelease;
        private readonly List<TKey> press;
        private Queue<KeyTime> release;

        private readonly Dictionary<TKey, bool> states;
        private readonly Stopwatch watch;
        private static readonly TimeSpan delta = TimeSpan.FromMilliseconds(20);

        public SetPressedStrategy(Action<TKey> onPress, Action<TKey> onRelease)
        {
            this.onPress = onPress;
            this.onRelease = onRelease;
            press = new List<TKey>();
            release = new Queue<KeyTime>();
            states = new Dictionary<TKey, bool>();
            watch = new Stopwatch();
            watch.Start();
        }

        public void Do()
        {
            while (release.Count != 0 && watch.Elapsed - release.Peek().Time > delta)
                onRelease(release.Dequeue().Key);

            press.ForEach(Press);
            press.Clear();
        }

        public void Add(TKey code)
        {
            if(!press.Contains(code))
                press.Add(code);
        }

        public void Add(TKey code, bool state)
        {
            if(state && (!states.ContainsKey(code) || !states[code]))
                Add(code);

            states[code] = state;
        }

        private void Press(TKey code)
        {
            onPress(code);
            release.Enqueue(new KeyTime {Key = code, Time = watch.Elapsed});
        }

        private struct KeyTime
        {
            public TKey Key { get; set; }
            public TimeSpan Time { get; set; }
        }

    }

    public class SetPressedStrategy : SetPressedStrategy<int>
    {
        public SetPressedStrategy(Action<int> onPress, Action<int> onRelease) : base(onPress, onRelease){}
    }
}
```

**Comment by MarijnS95** [comment]
@AndersMalmgren That sounds like a different problem. If I understand correctly, the button stays on all the time, and is only turned off when another midi message is processed (explaining the turn in the other direction, which does not call `setPressed` for the opposite direction).

**Comment by AndersMalmgren** [comment]
@MarijnS95 yeah. But never the less, we  should implement beter setpressed logic at some point :D

**Comment by AndersMalmgren** [comment]
Also there was a one tick input lag in the setpressed strategy, I now update set press directly. Havent tested the code

**Comment by vinKaiZen** [comment]
would you please show me how it could be? (starting with phyton & freepie since this night :/)

**Comment by vinKaiZen** [comment]
I´ve changed this

```
vJoy[0].setPressed(37, 0)
vJoy[0].setPressed(38, 0)

def update():
    diagnostics.watch(midi[0].data.channel)
    diagnostics.watch(midi[0].data.status)
    diagnostics.watch(midi[0].data.buffer[0])
    diagnostics.watch(midi[0].data.buffer[1])

    #Rotary LEFT
    if midi[0].data.buffer[0] == 2:
        vJoy[0].setPressed(37)
    
    #Rotary RIGHT
    if midi[0].data.buffer[0] == 3:
        vJoy[0].setPressed(38)

if starting:
    midi[0].update += update
```

**Comment by vinKaiZen** [comment]
I've tried serveral things i found
'''import time
   time.sleep(0.5)''' and something with timeout but all will bestes issues immediately :(

**Comment by vinKaiZen** [comment]
Finally this code works without any issues :)
Thread can be closed
````
import time
time.sleep(0.02)

vJoy[0].setPressed(37, 0)
vJoy[0].setPressed(38, 0)

def update():
    #Rotary LEFT
    vJoy[0].setPressed(37, midi[0].data.buffer[0] == 2)
    
    #Rotary RIGHT
    vJoy[0].setPressed(38, midi[0].data.buffer[0] == 3)
        
if starting:
    midi[0].update += update´´´
