### ISSUE TITLE
ValueError: Procedure probably called with too many arguments (4 bytes in excess)

### ISSUE THREAD

**Issue by tyler201** [AndersMalmgren/FreePIE#170]
Hello, I am trying to figure out how to use the FreepieIO dll, but have ran into some problems. I don't think this technically goes here, but running this code: 

```
import ctypes  # Module for c libaries
q = ctypes.WinDLL("E:\\Program Files (x86)\\FreePIE\\freepie_io.dll")  # Load DLL
slots = q.freepie_io_6dof_slots()
print(q.freepie_io_6dof_write(0))
print(slots)
```
Throws this error:
```
E:\Tyler\Documents\MKDJ\venv\Scripts\python.exe E:/Tyler/Documents/MKDJ/vjoy.py
Traceback (most recent call last):
  File "E:/vjoy.py", line 11, in <module>
    print(q.freepie_io_6dof_write(0))
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
```
Any ideas how I can fix this?

**Comment by MarijnS95** [comment]
Looking at the function definition, it seems you're actually calling the function with *too little* arguments.
https://github.com/AndersMalmgren/FreePIE/blob/11a4729e675cc79e26ecbb83d255c7569d02a155/Lib/IO/Code/src/freepie_io_6dof.cpp#L101-L104
Of course, you'll have to pass in actual values for the 6 degrees of freedom you're trying to set. The function allows setting multiple slots with these, and requires to pass in a pointer to one or more 6dof structs of the following format:
https://github.com/AndersMalmgren/FreePIE/blob/11a4729e675cc79e26ecbb83d255c7569d02a155/Lib/IO/Code/include/freepie_io.h#L10-L19
Note that you can make these structures relatively easy in ctypes.

**Comment by AndersMalmgren** [comment]
I do not remember why we did it like we did, but the first value is the start index to write from the  array. THe second is the number of elements to write and the third is the actual array of structs.
So lets say you hava a array of 4 structs and want to write them all you should pass 0, 4, arr

**Comment by tyler201** [comment]
In which case, I now have this as my main code:
```
class freepie_io_6dof_data(ctypes.Structure):
    __fields__ = [
        ("Yaw", ctypes.c_float),
        ("Pitch", ctypes.c_float),
        ("Roll", ctypes.c_float),
        ("X", ctypes.c_float),
        ("Y", ctypes.c_float),
        ("Z", ctypes.c_float)]

q = ctypes.WinDLL("E:\\Program Files (x86)\\FreePIE\\freepie_io.dll")  # Load DLL
slots = q.freepie_io_6dof_slots()
data = freepie_io_6dof_data()
data.Y = 0.312
q.freepie_io_6dof_write(0, 1, data)
```
And after running the program, I get this:
`Process finished with exit code -1073741819 (0xC0000005)`
My code in freepie is this:
```
def update():
	diagnostics.watch(freePieIO[0].y)
if starting:
	freePieIO[0].update += update
```
However, the value for y does not change in the software. Is there something I am missing?

**Comment by AndersMalmgren** [comment]
you need to stream continuously , freepie ignores stale data

https://github.com/AndersMalmgren/FreePIE/blob/11a4729e675cc79e26ecbb83d255c7569d02a155/FreePIE.Core.Plugins/FreePieIOPlugin.cs#L70

**Comment by MarijnS95** [comment]
You have to pass in a pointer to the 6dof datastructure. Right now the struct is passed by value, and the first two floats get interpreted as pointer to this struct, resulting in the access violation exception `0xC0000005`.

To solve this, pass `byref(data)` to the function instead. This passes the address instead of the value. (Use `from ctypes import byref` to get it).

**Comment by tyler201** [comment]
I tried that, and now I am 12 bytes in excess again. Here is my new code.

class freepie_io_6dof_data(ctypes.Structure):
    __fields__ = [
        ("Yaw", ctypes.c_float),
        ("Pitch", ctypes.c_float),
        ("Roll", ctypes.c_float),
        ("X", ctypes.c_float),
        ("Y", ctypes.c_float),
        ("Z", ctypes.c_float)]

q = ctypes.WinDLL("E:\\Program Files (x86)\\FreePIE\\freepie_io.dll")  # Load DLL
slots = q.freepie_io_6dof_slots()
data = freepie_io_6dof_data()
data.Y = 0.312
while True:
    q.freepie_io_6dof_write(0, 1, byref(data))

**Comment by MarijnS95** [comment]
If my memory serves me right, you should set the parameter types for the function in advance, otherwise it defaults to integer inputs only.

Try setting it with:
```python
q.freepie_io_6dof_write.argtypes = [c_int, c_int, POINTER(freepie_io_6dof_data)]
```

Of course, import those names from ctypes.

**Comment by tyler201** [comment]
So if how I interpret that is correct, this should be my code now?
```
import ctypes  # Module for c libaries
from ctypes import byref, c_int, POINTER


class freepie_io_6dof_data(ctypes.Structure):
    __fields__ = [
        ("Yaw", ctypes.c_float),
        ("Pitch", ctypes.c_float),
        ("Roll", ctypes.c_float),
        ("X", ctypes.c_float),
        ("Y", ctypes.c_float),
        ("Z", ctypes.c_float)]

q = ctypes.WinDLL("E:\\Program Files (x86)\\FreePIE\\freepie_io.dll")  # Load DLL
slots = q.freepie_io_6dof_slots()
data = freepie_io_6dof_data()
data.Y = 0.312
q.freepie_io_6dof_write.argtypes = [c_int, c_int, POINTER(freepie_io_6dof_data)]
while True:
    q.freepie_io_6dof_write(0, 1, byref(data))
```
However I still have the same warning.

**Comment by AndersMalmgren** [comment]
Maybe the sample can give you some ideas

https://github.com/AndersMalmgren/FreePIE/blob/master/Lib/IO/Code/test/main.c

**Comment by MarijnS95** [comment]
This seems more and more like a calling convention issue. `WinDLL` considers stdcall whereas the Microsoft C++ compiler (by default) outputs functions with `cdecl`. Try replacing `WinDLL` with `CDLL`.

**Comment by tyler201** [comment]
Okay! Now I'm getting somewhere! Using @MarijnS95 answer, I'm now getting a readout in freepie. However, the number changes each time I run the python file, and I assume that has something to do with the pointer. Here is my up to date code:
```
class freepie_io_6dof_data(ctypes.Structure):
    __fields__ = [
        ("Yaw", ctypes.c_float),
        ("Pitch", ctypes.c_float),
        ("Roll", ctypes.c_float),
        ("X", ctypes.c_float),
        ("Y", ctypes.c_float),
        ("Z", ctypes.c_float)]

q = ctypes.CDLL("E:\\Program Files (x86)\\FreePIE\\freepie_io.dll")  # Load DLL
slots = q.freepie_io_6dof_slots()
data = freepie_io_6dof_data()
data.Y = 0
q.freepie_io_6dof_write.argtypes = [c_int, c_int, POINTER(freepie_io_6dof_data)]
while True:
    q.freepie_io_6dof_write(0, 1, byref(data))
```

**Comment by MarijnS95** [comment]
@tyler201 Have you found the issue already? I haven't commented because I didn't know either, but now notice that you have `__fields__` with two underscores instead of one: `_fields_`. That should be it, given that the structure size is 0 so that the library interprets random (uninitialized) data "after" the pointer/structure as `freepie_io_6dof_data`.

**Comment by tyler201** [comment]
Hi, it took me a while to notice, but I did and the code has been running beautifully while I've been using it. Thank you to all who tried to help!
