### ISSUE TITLE
Feature request - script execution in background

### ISSUE THREAD

**Issue by darmach** [AndersMalmgren/FreePIE#172]
It would be very convenient to be able to execute script in FreePIE and keep it running in the background.
Maybe with a command line switch?

Is there such functionality, or maybe it's possible to compile/package the script such way?

**Comment by AndersMalmgren** [comment]
Btw, you can also build the console project, under FreePIE.Console

**Comment by darmach** [comment]
Awesome! Thank you very much!

**Comment by AndersMalmgren** [comment]
It might need the latest and greatest version. Sorry not that active in the project anymore, can you build the latest version yourself?

**Comment by AndersMalmgren** [comment]
Hmm, checked the git log, and the feature should be in the version that is in the latest installer

**Comment by AndersMalmgren** [comment]
Or wait, here is the log, even though the date on that commit is older than latest version we pulled it in later than the release it seems.

![image](https://user-images.githubusercontent.com/817577/51538376-62c87780-1e51-11e9-862f-0ba58f4c27b2.png)

**Comment by AndersMalmgren** [comment]
@darmach I just released new binary

https://github.com/AndersMalmgren/FreePIE/releases

**Comment by darmach** [comment]
You're great, works perfect! What a beautiful world would that be if commercial products would have such a professional level of support!

**Comment by AndersMalmgren** [comment]
:) thanks bud. Sadly I neglect Freepie, have too much on my table :/
