### ISSUE TITLE
Script resource cleanup

### ISSUE THREAD

**Issue by svofski** [AndersMalmgren/FreePIE#177]
I'm interfacing with a custom made controller on a serial port. I'm using .net SerialPort, like so: 

```
from System.IO.Ports import SerialPort
...
if starting:
    serial = SerialPort('COM8', 115200);
    serial.Open()
```

This works fine, however the script is lacking any means of cleanup and FreePIE does not know about resources used by the script either. So after running the script once, I must restart FreePIE, lest the serial port stays open by the previous instance. This makes debugging the script a slightly nauseous experience.

Please add some means of cleaning up, or properly dispose of the environment in which the script runs.

**Comment by AndersMalmgren** [comment]
Can't you use the stopping variable? It's true once when the script is stopping

**Comment by svofski** [comment]
Oh, I didn't realize it exists. That will help indeed, thanks. However the scripts may also throw an exception. Is there a way to add a kind of finally clause to a script?

**Comment by AndersMalmgren** [comment]
You can use python for it 

https://www.w3schools.com/python/python_try_except.asp

**Comment by svofski** [comment]
Oh you mean in the script body. Yes it should work. Thanks!
