### ISSUE TITLE
Crash if started script, stopped, introduced an error, started.

### ISSUE THREAD

**Issue by wadim-al** [AndersMalmgren/FreePIE#179]
Problem: if script was run, stopped, edited so error was introduced and started the app crashes.

OS: Windows 10 x64
FreePIE: 1.11.724.0

Steps. 
1. Open orbiter.py
2. Start script
3. Stop script
4. Uncomment lines 34 and 35 to introduce variable not defined error
5. Repeat the steps until crashed.

[orbiter - Copy.py.txt](https://github.com/AndersMalmgren/FreePIE/files/3537888/orbiter.-.Copy.py.txt)
[FreePIE.exe.3692.dmp.txt](https://github.com/AndersMalmgren/FreePIE/files/3537889/FreePIE.exe.3692.dmp.txt)

**Comment by AndersMalmgren** [comment]
[FreePIE.Core.Plugins.zip](https://github.com/AndersMalmgren/FreePIE/files/3540399/FreePIE.Core.Plugins.zip)

Please try this version, I did a small fix to the hydra plugin. Make sure that the dll is not blocked since its downloaded from internet

**Comment by wadim-al** [comment]
When running the following script with the new dll:
vJoy[0].x= hydra[0].joyx
I'm getting 2 errors: 
An item with the same key has already been added.
Object reference not set to an instance of an object.
![FreePIE_2019-08-26_13-10-41](https://user-images.githubusercontent.com/29713984/63683557-636c2680-c803-11e9-8e82-1c15fead9970.png)

**Comment by wadim-al** [comment]
After replacing the new .dll I've started getting errors. 
Errors:
an item with the same key has already been added
object reference not set to an instance of a object
Reinstalling the FreePIE did not help. Don't know how to recover. Registry cleaning? regsvr dll unregister?
![FreePIE_2019-08-26_13-10-41](https://user-images.githubusercontent.com/29713984/63684150-e477ed80-c804-11e9-91f5-9d1147133fdc.png)

**Comment by AndersMalmgren** [comment]
Strange all I changed from the released version is a small thing in how we handel errors in hydra

**Comment by wadim-al** [comment]
Will try to remove all references of that dll from the registry, plus all reg keys for FreePIE which I will find.

**Comment by wadim-al** [comment]
I was able to cleanly reinstall. Still after adding a new dll I'm getting the same errors. Was able to return back to original dll.

**Comment by AndersMalmgren** [comment]
And you have made sure its not blocked?

**Comment by AndersMalmgren** [comment]
![image](https://user-images.githubusercontent.com/817577/63691075-8cde7f80-c80e-11e9-8cad-6ffe28352335.png)

**Comment by wadim-al** [comment]
There is no Unblock checkbox for this file on my Win10.
You can try this dll yourself and use any script like 'keyboard.setPressed(Key.A, Key.B)' to see if you will have those errors. Hydra not needed.

**Comment by AndersMalmgren** [comment]
It seems .net is a bit funny. Could it be you hava  renamed old file to dllold, dllbak os similar

![image](https://user-images.githubusercontent.com/817577/63692892-01b3b880-c813-11e9-8224-ab44344ed387.png)

**Comment by AndersMalmgren** [comment]
I'll fix that for next version of freepie

```csharp
            var dlls = fileSystem
                .GetFiles(path, "*.dll")
                .Where(dll => dll.EndsWith("dll", StringComparison.InvariantCultureIgnoreCase))
                .ToList();
```

**Comment by wadim-al** [comment]
I confirm, that I've renamed the dll to dll1

**Comment by wadim-al** [comment]
Tested the new dll, without old. Now it is not crashing. Fixed. Thanks!
