### ISSUE TITLE
Question: how to invert the right stick of an xbox360 controller?

### ISSUE THREAD

**Issue by Drugbird** [AndersMalmgren/FreePIE#186]
I'm trying to play a game that does not support inverted camera, so I'd like to invert the right analog stick of an xbox360 controller.

So far I've tried this script:

`xbox360[0].rightStickX = -1 * xbox360[0].rightStickX
xbox360[0].rightStickY = -1 * xbox360[0].rightStickY`

However, that gives me the error:

> can't assign to read-only property rightStickX of type 'XBox360PluginGlobal'

I see no update method, or setRightStick methods available in the xbox360 structure, so I'm unsure how to proceed.

How can I invert the right stick of an xbox controller?

Thanks in advance.

**Comment by AndersMalmgren** [comment]
Xbox 360 is a read only plugin. You can send the inpur through vjoy which outputs virtual joysticks

**Comment by Drugbird** [comment]
Great, I'll give that a try this evening. Thanks for the quick reply and showing me which direction to go.

**Comment by Drugbird** [comment]
I've had a look at the vJoy documentation, and it seems to only support a single analog stick. Since the xbox360 controller has two sticks, it seems I'm unable to map both analog sticks to the vJoy. I would appreciate any suggestions on how to proceed.

**Comment by AndersMalmgren** [comment]
You can use the rotation axis for that. Accesible through freepie 

`vJoy[0].rx`

**Comment by Drugbird** [comment]
Thanks!
