### ISSUE TITLE
Your installer download link is broken

### ISSUE THREAD

**Issue by machupicchu27** [AndersMalmgren/FreePIE#190]
"The connection for this site is not secure

github-production-release-asset-2e65be.s3.amazonaws.com sent an invalid response."

**Comment by AndersMalmgren** [comment]
Just tried it works, https://github.com/AndersMalmgren/FreePIE/releases/download/1.11.724/FreePIE.1.11.724.0.msi

**Comment by machupicchu27** [comment]
My bad, problem with my network. Thanks
