### ISSUE TITLE
Multiple Keyboard support?

### ISSUE THREAD

**Issue by speed-of-heat** [AndersMalmgren/FreePIE#204]
would it be possible to provide multiple keyboard support so that we can enumerate keyboard devices, and selectively take input from and supress output from the specific keyboard device?  keyboard[0].xxxx etc.

**Comment by AndersMalmgren** [comment]
We never got suppression of keyboard events to work. If you want to give it a go I happily pull the changes.

**Comment by speed-of-heat** [comment]
alas thats beyond my capabilities; a good dev has to know their limitations :) thanks for the clarification though! I think the only practical and repeatable way of doing it is with a kernel mode driver...
