### ISSUE TITLE
Time not imported?

### ISSUE THREAD

**Issue by AfromD** [AndersMalmgren/FreePIE#205]
the code 
`t_start = time.time()`
results in error message "name 'time' is not defined"
Since time is a standard python library I thought it should be imported automatically. I did not include an import statement.
How do I get the current system clock for measuring time?

**Comment by subash017** [comment]
You should import time library in order to use it.

**Comment by AfromD** [comment]
Thank you, that worked. For some reason it did not help before, which added to the confusion. I thought that importing was already done by Freepie as the wiki says on syntax:
`FreePIE even includes the standard Python libs, importing them automatically so that you can use them in your script - even without using import statements:`
It seems this is not correct.
