### ISSUE TITLE
Script to use Mouse Scroll or Incremental Rotary encoder to Steering Wheel Accurately

### ISSUE THREAD

**Issue by nosazik** [AndersMalmgren/FreePIE#211]
I want to use Vjoy Codes mouse.wheelUp , mouse.wheelDown , mouse.wheel , mouse.wheelMax. Rotary Mouse Encoder to make Diy steering wheel.
Anyone know a script can make X axis move smoothing.
Like a steering = steering + ((float(mouse.deltaX) * mouse_sensitivity) / steering_center_reduction)
But need to calculate the speed too.
i don't know how to do, so aprecciate if someone help me.
Rotary Encoder coding

**Comment by AndersMalmgren** [comment]
Have you looked at?

filters.simple
filters.deadband
filters.mapRange
filters.ensureMapRange


They might be of help
