### ISSUE TITLE
Cannot access CORE file

### ISSUE THREAD

**Issue by Shi-Gi** [AndersMalmgren/FreePIE#215]
Whenever I run a script, it says, "Access to the path 'C:/Users/Brian/AppData/Local/Temp/FreePIE.Core.Plugins.dll' is denied." I tried turning off antivirus but I can't even find the folder it's talking about in Temp to try to give it unrestricted access. Have you seen this issue before and know of any fixes. If it's of any use to you, I'm trying to use the software for Project Wingman trackIR support.
![ghdfghdf](https://user-images.githubusercontent.com/106294936/170415384-1714cfe1-bf59-4667-94a0-8f35051ece8d.PNG)
?

**Comment by AndersMalmgren** [comment]
It seems to haven't intalled it to a folder with normal rights. You need to run the program as admin or reinstall it under programs folder

**Comment by Shi-Gi** [comment]
I thought I tried running it as admin but I must have messed up somewhere when doing that because it worked this time when I ran it as admin! Thanks a bunch!

**Comment by AndersMalmgren** [comment]
> I thought I tried running it as admin but I must have messed up somewhere when doing that because it worked this time when I ran it as admin! Thanks a bunch!

Just keep in mind this shouldn't be needed if it's installed as intended
