### ISSUE TITLE
我的Freepie无法正常运行代码

### ISSUE THREAD

**Issue by Brush-XD** [AndersMalmgren/FreePIE#222]
![微信图片_20230305180738](https://user-images.githubusercontent.com/127019146/222954072-12f5b0e4-6d70-407a-9d3f-09f5a2dc6ee8.png)
图片中显示的错误代码为 找不到方法:"System.Collections.Generic.IEnumerable`1<!!0>Microsoft.Scripting.Utils.ReflectionUtils.GetCustomAttributes(System.Reflection.Assembly, Boolean)"
每次一点击run script便会显示此项并且无法运行代码
由于我对电脑代码完全不了解，我完全不理解错误代码显示的问题所在。
我已经尝试了所以我能使用的方法去解决这个问题但毫无效果，希望得到一些帮助。
感激不尽！

**Comment by AndersMalmgren** [comment]
你能提供英文代码吗，谢谢

**Comment by Brush-XD** [comment]
Method not found: 'System.Collections.Generic.lEnumerable`1<!!0>Microsoft.Scripting.Utils.ReflectionUtils.GetCustomAttributes(System.Reflection.Assembly, Boolean)'.
希望这是你需要的，以下是我试图运行的代码，这些代码在几天前仍然是可以工作的
`from ctypes import *
user32 = windll.user32 # 调用鼠标锁定功能所需库

if starting:
	# 功能开关
	vjoyaxis = True # 转向轴与踏板开关
	mouselock = False # AC鼠标位置锁定（隐藏）专属开关（这里不要修改，后面可以设置开关快捷键）
	# 映射vJoy设备号
	v = vJoy[0]
	# vjoy最大轴行程，勿改！
	a_max = 4 + v.axisMax
	a_min = -4 - v.axisMax
	# 鼠标转向
	m_sens = 22.5	# 鼠标灵敏度，数值越大转向越快
	m_redu = 2.15 # 中心缩减，合理数值范围1-50设置为1时即无中心缩减。
	steering = 0 # 勿改！
	center_redu = 1 # 勿改！
	# 油门
	th_axis = a_min # 勿改！
	th_inc = 1500 # 油门提升速率，数值越大油门提升越快
	th_dec = 2000 # 松油速率，数值越大松油越快
	# 刹车
	br_axis = a_min # 勿改！
	br_inc = 1800 # 刹车提升速率，数值越大油门提升越快
	br_dec = 2000 # 松刹速率，数值越大松刹越快
	# 手刹
	ha_axis = a_min # 勿改！
	ha_inc = 6000
	ha_dec = 6000
	# 离合
	cl_axis = a_min # 勿改！
	cl_inc = 6000
	cl_dec = 6000

#======== 键位映射 ========#
# 开关
toggle_mouselock = keyboard.getPressed(Key.End) # AC用鼠标锁定（隐藏）
# 车辆控制
key_throttle = mouse.getButton(0) # 油门
key_brake = mouse.getButton(1) # 刹车
key_handbrake = keyboard.getKeyDown(Key.Q) # 手刹
key_clutch = keyboard.getKeyDown(Key.C) # 离合
key_centerx = mouse.getButton(2) # 转向回中
key_shiftup = keyboard.getKeyDown(Key.S) # 升档
key_shiftdown = keyboard.getKeyDown(Key.X) # 降档
key_changecamera = keyboard.getKeyDown(Key.V) #切换视角
key_headlight = keyboard.getKeyDown(Key.L) #大灯
key_Glanceleft = keyboard.getKeyDown(Key.W) #向左看
key_Glanceright = keyboard.getKeyDown(Key.E) #向右看
key_Horn = keyboard.getKeyDown(Key.H) #鸣笛
key_flashheadlight = keyboard.getKeyDown(Key.K) #闪头灯
#======== 鼠标隐藏开关 ========#
if toggle_mouselock:
	mouselock = not mouselock

#======== 转向轴与踏板 ========#
if (vjoyaxis):
	#======== 鼠标锁定 ========#
	if (mouselock):
		user32.SetCursorPos(200 , 5000) # 鼠标在屏幕上的像素坐标(x, y)，AC专用
	# 鼠标转向
	if steering > 0:
		center_redu = m_redu ** (1 - (steering / a_max))
	elif steering < 0:
		center_redu = m_redu ** (1 - (steering / a_min))
	steering += (mouse.deltaX * m_sens) / center_redu
	if steering > a_max:
		steering = a_max
	elif steering < a_min:
		steering = a_min
	if key_centerx:
		steering = 0
	# 油门轴
	if key_throttle:
	    th_axis += th_inc
	else:
	    th_axis -= th_dec
	if th_axis > a_max:
	    th_axis = a_max
	elif th_axis < a_min:
	    th_axis = a_min
	# 刹车轴
	if key_brake:
	    br_axis += br_inc
	else:
	    br_axis -= br_dec
	if br_axis > a_max:
	    br_axis = a_max
	elif br_axis < a_min:
	    br_axis = a_min
	# 手刹轴
	if key_handbrake:
	    ha_axis += ha_inc
	else:
	    ha_axis -= ha_dec
	if ha_axis > a_max:
	    ha_axis = a_max
	elif ha_axis < a_min:
	    ha_axis = a_min
	# 离合轴
	if key_clutch:
	    cl_axis += cl_inc
	else:
	    cl_axis -= cl_dec
	if cl_axis > a_max:
	    cl_axis = a_max
	elif cl_axis < a_min:
	    cl_axis = a_min

#======== vjoy 轴与按钮映射（勿随便修改） ========#
v.x = int(round(steering))
v.y = th_axis
v.z = br_axis
v.ry = ha_axis
v.rx = cl_axis
v.setButton(0,key_shiftup)
v.setButton(1,key_shiftdown)
v.setButton(2,key_changecamera)
v.setButton(3,key_headlight)
v.setButton(4,key_Glanceleft)
v.setButton(5,key_Glanceright)
v.setButton(6,key_Horn)
v.setButton(7,key_flashheadlight)`

**Comment by Brush-XD** [comment]
Method not found: 'System.Collections.Generic.lEnumerable`1<!!0>Microsoft.Scripting.Utils.ReflectionUtils.GetCustomAttributes(System.Reflection.Assembly, Boolean)'.
不好意思上面缺了一个标点

**Comment by Brush-XD** [comment]
You did not reply to me, perhaps because I did not understand your meaning and provided the wrong content, so I changed all the comments into English.
I would appreciate it if you could simply provide me with a solution or a reason for the error. It's been a long time since I've enjoyed playing my favorite game.(CRYING)
[vjfreepie_全新控制脚本精简版抓地.py.txt](https://github.com/AndersMalmgren/FreePIE/files/11146140/vjfreepie_.py.txt)
`

**Comment by masyanius** [comment]
Uninstall IronPython, it's working for me now

**Comment by Brush-XD** [comment]
很幸运地，我已经解决了这个问题

**Comment by masyanius** [comment]
Sorry for deleting my reply, thought it not worked.
Uninstalling IronPython solved it for me
