### ISSUE TITLE
Compile script to standalone executable?

### ISSUE THREAD

**Issue by jscottee** [AndersMalmgren/FreePIE#225]
Can I compile a FreePIE script as a standalone executable? For example, I have written a script that I'd like to be able to run easily when I'm opening a game.

I don't have any C# experience, so details are appreciated.

I saw someone asked this question on the Meant to be Seen `[FAQ Board](https://www.mtbs3d.com/phpbb/viewtopic.php?t=22851)` a few years ago, but it didn't get any answers.

**Comment by AndersMalmgren** [comment]
Hi, no bit you can open and run it from the command line freepie.exe file /r

**Comment by jscottee** [comment]
Thanks!
