### ISSUE TITLE
FreePIE does not work with my new x64 plugin (and the plugin does not work when compiled to x86)

### ISSUE THREAD

**Issue by JabberwockPL** [AndersMalmgren/FreePIE#231]
I am trying to write a new plugin for the newer drivers for Ultraleap/Leap Motion controllers. Unfortunately, right at the start I have hit a snag: while the plugin loads into FreePIE while compiled for Any CPU/x86, any attempt to actually use it throws the error: attempt to load program with incorrect format 0x8007000B. I have tried to compile it for x64, but then FreePIE just crashes (as most likely it expects only 32-bit plugin).  Is there any chance to make FreePIE work with x64 plugins?

**Comment by AndersMalmgren** [comment]
Compiling freepie for x64 is easy but it will probably have side effects. You can try if you want. 

The reason its x86 is because at the time alot of people still used x86 systems :)

**Comment by JabberwockPL** [comment]
Of course, that is understandable. I just did not know they have to be exclusive.

As I understand, if I recompile for x64, all other external plugins will stop working in turn? It still might be worth it, I guess.

**Comment by AndersMalmgren** [comment]
It should work, but you know of it is. 

Edit: it should work meaning x64 compiled freepie should be able to invoke x86 dlls. But it might be side effects

**Comment by JabberwockPL** [comment]
Well, for now it works - it runs and displays the number of hands seen by Leap. It did throw some warnings concerning other plugins (SlimDX, Vjoy and others), so possibly I will need to look into that as well. Right now I will develop the plugin itself.

Thank you for your help!

**Comment by JabberwockPL** [comment]
I was a bit quick - copying ANY of the plugin files (including Core.Plugins and Contracts) causes x64 version to hang... Some more work will be needed.

**Comment by AndersMalmgren** [comment]
Sorry i was a bit tired when I wrote earlier, im in holiday mode. 

X86 assemblies can only be hosted by a x86 process and vice versa.

**Comment by JabberwockPL** [comment]
No worries - I just needed to hunt down all the x64 versions of dependencies in Lib. Now everything works perfectly! Of course, external plugins would also need to be recompiled, but that I can live with, most of them are open sourced anyway.

**Comment by drowhunter** [comment]
I'm very interested in this leap plugin.  could you try it on this 64-bit fork ?

https://github.com/Ofisare/FreePIE

**Comment by JabberwockPL** [comment]
I am not trying to be difficult, but if the GitHub page mentioned it is a x64 fork, I would have spent the afternoon somewhat differently, like writing the plugin ;) Seriously though: did you replace all the 32-bit library dependencies? Because finding them took most of my time...

The plugin already works on my 64-bit version, but I have just started to see if it does, so it does not do much yet. (I am reusing mostly code from https://github.com/sctaylor/LeapCSharpExample/ Steve has been quite helpful). For now I was thinking just position of hands/fingers, some basic gestures maybe (I guess I will start a GitHub page for it soon, no point in spamming here).

**Comment by JabberwockPL** [comment]
One adverse effect I did not notice before: mouse.delta no longer works...
The issue seems to be related to the public struct INPUT section - the offsets should be different:
            [FieldOffset(0)]
            public int type;
            [FieldOffset(8)]
            public MOUSEINPUT mi;
            [FieldOffset(8)]
            public KEYBDINPUT ki;
            [FieldOffset(8)]
            public HARDWAREINPUT hi;
