### ISSUE TITLE
Add support for XInput write

### ISSUE THREAD

**Issue by Jahdrien** [AndersMalmgren/FreePIE#26]
Current xbox360 plugin only allows to map xbox controllers output, but one of the last works in GlovePIE was to support writing XInput output. This would allow to emulate Xbox360 controller using only FreePIE instead of FreePIE + vJoy + x360ce...

**Comment by AndersMalmgren** [comment]
This is now possible with a stand alone plugin

https://github.com/dschu012/XOutputPlugin

Might incorporate this in FreePIE when I get the time

**Comment by yabix007** [comment]
Is it possible to send rumble for xbox360 in Freepie?
