### ISSUE TITLE
Mouse cursor will not move when TriDef ignition 3D has focus. 

### ISSUE THREAD

**Issue by deathentry** [AndersMalmgren/FreePIE#40]
I have been using the FreePie Android IMU for head tracking in my colorcross HMD. The mouse cursor moves in response to my phone until I give TriDef ignition focus, the mouse refuses to move despite the values in the watch window seemingly still responding to my phone movements.. 

This means that any game launched via TriDef for 3D SBS cannot use FreePie for head tracking... 

Oddly giving any other program focus restores the mouse moment including launching games directly, outside of TriDef

**Comment by BlueSkyDefender** [comment]
Same Problem here with any 3D application I lose mouse control.

**Comment by thehiderofkeys** [comment]
Keyboard and Mouse input will also stop updating when games are in focus. This problem is resolved when launched in admin mode as stated by BlueSkyDefender

**Comment by AndersMalmgren** [comment]
Solved as of above
