### ISSUE TITLE
Wrong yaw data (X axis drift) [SOLVED]

### ISSUE THREAD

**Issue by Gpinchon** [AndersMalmgren/FreePIE#46]
Hi,
I'm having an issue with FreePIE on Android, the yaw value seems to be going crazy.
Everytime I move y head on the pitch axis (even slightly) the yaw value increases (or decreases) very fast, even if I stop moving my head.
Gyroscope Explorer indicates that the X, Y and Z values are normal and stable, the only abnormal value I noticed was when activating "Fusion", the "FusedGyroscopeCalibratedSensor" seems to drift slowly on the X axis... So, perhaps the app should use the "uncalibrated" data...
By the way, I'm using an HTC One with Custom Sense ROM and latest firmware so it's not a Gyroscope's driver issue.

**Comment by lansings** [comment]
Hello, I have the same problem. I'm using an Xiaomi Mi4.
In other apps, like android VR apps or trinusvr/riftcar everything is ok, but i cant use freepie (v 1.9.629, 1.8, 1.5) because X axis "works" like Gpinchon have described
