### ISSUE TITLE
android debug not as efficient as ought to be

### ISSUE THREAD

**Issue by sthalik** [AndersMalmgren/FreePIE#57]
With last pull request I introduced a regression in

    private TimerTask debugHandler = new TimerTask() {
Please change

                public void run() {
                    if (udpSenderService != null) {
to

                public void run() {
                    if (chkDebug.isChecked() && udpSenderService != null) {

It allocates a memory constructing these <code>float[]</code>s several times a second and it shouldn't.

regards,
-sh

**Comment by sthalik** [comment]
You can even also move the <code>float[]</code> variables to the class to avoid constructing them even in debug case.

**Comment by sthalik** [comment]
Hi @AndersMalmgren any luck?

**Comment by AndersMalmgren** [comment]
Sorry haven't had time to look at this,  vacation with family etc

**Comment by AndersMalmgren** [comment]
If you fix this i will pull it

**Comment by sthalik** [comment]
I'm having some problems with Android Studio. It changes directory layout on import. How are you developing the android plugin?

**Comment by AndersMalmgren** [comment]
I havent moved to Android Studio, I still use Ecplise with the plugin. I know, I am slow :D

**Comment by sthalik** [comment]
See #63

**Comment by sthalik** [comment]
Done as per #63

**Comment by sthalik** [comment]
@AndersMalmgren please drop us an .apk. Cheers!

**Comment by AndersMalmgren** [comment]
Here is the version from latest install of FreePIE

https://dl.dropboxusercontent.com/u/33026505/com.freepie.android.imu.apk

**Comment by sthalik** [comment]
@AndersMalmgren thank you!
