### ISSUE TITLE
android lacks copyright statement

### ISSUE THREAD

**Issue by sthalik** [AndersMalmgren/FreePIE#59]
@AndersMalmgren please add your copyright to Android .apk sources. I don't know how to credit you in a 3rdparty credit notice for the .apk that we bundle.

I'd also like to add my BSD copyright to some files. It's best if we add copyright to each separate source file.

If this is overkill, I'll add a thanks notice.

**Comment by AndersMalmgren** [comment]
Right now its under FreePIE license which is GPLv2 because of some depecnides to GPLv2 libraries. I guess its ok to license the Android folder in the project under a different license. I'm stil out of town on vacation, so cant look at it for a while. About your bugs, could you do a pull request?

**Comment by sthalik** [comment]
Hey,

You can use any license you want with GPLv2 as long as it places less or same restrictions as GPL.

I can also do a pull request with license changes if you specify license name, and your email optionally.

Also Android has no dependencies, and is separate from this issue altogether.

My license is fun and short btw:

    /* Copyright (c) 2014-2015 REALNAME <EMAIL>
     *
     * Permission to use, copy, modify, and/or distribute this software for any
     * purpose with or without fee is hereby granted, provided that the above
     * copyright notice and this permission notice appear in all copies.
     */

**Comment by sthalik** [comment]
I'll do a pull request with debug change soon.

**Comment by AndersMalmgren** [comment]
I'm really not a fan of clogging each source file with license text. (I know that you C guys like this :D). How about a license.txt under Android folder?

**Comment by sthalik** [comment]
Fine with me. Describe what you want in a pull request.

**Comment by sthalik** [comment]
The initial work was done by  alsomahler <rsteenbergen@sogyo.nl>

Does he agree on a license?

**Comment by AndersMalmgren** [comment]
I'm not a lawyer but my guess is that all code that is commited into FreePIE that is missing license info is defaulted to the license of FreePIE which is gpl?

**Comment by sthalik** [comment]
It's defaulted to no rights granted by the original author, unless you have a written grant agreement like FSF has.

That's why we use per-file license grants.

**Comment by AndersMalmgren** [comment]
There is not a C# project out there that I know how that pollutes all source files with license info. So I doubt that, but anyway I am the initial author of the Android folder

```
SHA-1: 24d33fa448fa0ec3aa0af627dff94497d54570f6

* Added first version of android app and FreePIE android plugin
```

**Comment by AndersMalmgren** [comment]
I pushed a license.txt to the android folder

**Comment by sthalik** [comment]
Back before the BSD lawsuit no license code defaulted to all rights granted. Now we have to learn all that useless overhead. Sheesh.

**Comment by sthalik** [comment]
Pull request; #60

**Comment by sthalik** [comment]
Thanks, looks like we're done here for now.
