### ISSUE TITLE
FreePIE settings corrupted

### ISSUE THREAD

**Issue by NixillUmbreon** [AndersMalmgren/FreePIE#62]
Something strange happened while using FreePIE recently, and the settings got corrupted. This had the effect of [rendering FreePIE silently unable to start](https://github.com/AndersMalmgren/FreePIE/issues/61).

I suspected that it had happened because of running the program as an administrator, but the idea was overturned because I just now did it after fixing the corrupt settings, and it opened fine. It might be that I turned off my computer without stopping the program first.

Suggested fix of silent opening: Bring up a dialog box saying "The settings are corrupted. Continuing your use of the program will reset it to default settings. Continue anyway?" with a yes or no. Yes will reset the settings file, no will terminate the program.

**Comment by AndersMalmgren** [comment]
Really strange I'm pretty sure we have  code that should reset the configuration if it fails to load.  Will look into it,  thanks
