### ISSUE TITLE
Support for VJoy 2.1.6

### ISSUE THREAD

**Issue by dwilkison** [AndersMalmgren/FreePIE#70]
Currently, FreePIE supports VJoy Interface 2.05. On October 9,2015, VJoy came out with a version 2.1.6 which does not work on the newest version of FreePIE.

**Comment by AndersMalmgren** [comment]
Thanks for heads up, will look into it when I get time

**Comment by dwilkison** [comment]
Actually, After replacing the old 2.0.5 vJoyInterface.dll with the 2.1.6 vJoyInterface.dll, everything started to map correctly :) Thanks again for all your hard work on this.

**Comment by AndersMalmgren** [comment]
Thanks for investigating will update SDK

**Comment by AndersMalmgren** [comment]
Strange, installed vjoy 0.2.1.6 and it still works with FreePIE

**Comment by AndersMalmgren** [comment]
Fixed with 3232597de2d2843f2052bb8ca87704842d9139ce
