### ISSUE TITLE
tobiiEyeX.gazePointNormalizedY uses value from tobiiEyeX.gazePointNormalizedX

### ISSUE THREAD

**Issue by Desrtfox** [AndersMalmgren/FreePIE#74]
tobiiEyeX.gazePointNormalizedY is not reading the Y position of the gazepoint.  Instead, it's duplicating the X value of the gazePoint.

**Comment by AndersMalmgren** [comment]
Good catch, there is a typo in the code

```csharp
public float gazePointNormalizedY { get { return plugin.NormalizedGazePoint.X; } }
```

https://github.com/AndersMalmgren/FreePIE/blob/master/FreePIE.Core.Plugins/TobiiEyeXPlugin.cs#L257

**Comment by Desrtfox** [comment]
Are you going to be producing a new executable or msi build?  I don't
currently have Git installed or a compiler on my PC.  I guess I can install
one though, if necessary.


On Sun, Jan 17, 2016 at 6:14 AM, Anders Malmgren <notifications@github.com>
wrote:

> Good catch, there is a typo in the code
>
> public float gazePointNormalizedY { get { return plugin.NormalizedGazePoint.X; } }
>
>
> https://github.com/AndersMalmgren/FreePIE/blob/master/FreePIE.Core.Plugins/TobiiEyeXPlugin.cs#L257
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndersMalmgren/FreePIE/issues/74#issuecomment-172324523>
> .
>



-- 
Not your Average News
<http://www.google.com/reader/shared/user/09576876109675415588/state/com.google/starred>

**Comment by AndersMalmgren** [comment]
Yes a new version is overdue, will try to get a new release out soon

**Comment by Desrtfox** [comment]
Turns out that I do have VS 2012 installed!  I was able to recompile the
coreplugins.dll.  It seems to be working fine now.  Thanks.

On Tue, Jan 19, 2016 at 4:18 PM, Anders Malmgren <notifications@github.com>
wrote:

> Yes a new version is overdue, will try to get a new release out soon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndersMalmgren/FreePIE/issues/74#issuecomment-173019729>
> .
>



-- 
Not your Average News
<http://www.google.com/reader/shared/user/09576876109675415588/state/com.google/starred>

**Comment by AndersMalmgren** [comment]
Cool!
