### ISSUE TITLE
Hydra head track

### ISSUE THREAD

**Issue by LukyLK** [AndersMalmgren/FreePIE#84]
Hello,
I'm trying to make  my hydra work as full motion headtracker.
Is there some easy way to make it via Freepie? I'm not gut in codes and my experiments falls.
Thank you.

**Comment by AndersMalmgren** [comment]
For script support please try the forum 

http://www.mtbs3d.com/phpBB/viewforum.php?f=139&sid=4ec196fc80e72314b18b8fb31e138a82
