### ISSUE TITLE
Would love to see this work with Vive controllers

### ISSUE THREAD

**Issue by thedonquixotic** [AndersMalmgren/FreePIE#85]
It would be awesome to see this work with Vive controllers. There are Oculus projects that use the Razer Hydra that would be awesome on Vive if only Vive controllers could emulate the Hydras. Will be following this project's progress for sure! If you guys get something working, try posting to /r/vive on reddit, it's a big community for the Vive base right now.

**Comment by AndersMalmgren** [comment]
Hi, im actually making a game for the Vive as we speak and dont have that much time at all for FreePIE sadly. If someone would like to get a go at it you could incorporate OpenVR into FreePIE
https://github.com/ValveSoftware/openvr

**Comment by thedonquixotic** [comment]
I'm just a designer/artist but hopefully someone else will see this too :)

A quick question also, maybe a kind of dumb one: it looks like it can already translate the Hydra to the Oculus Touch right? As far as I understand, Revive can actually emulate the Oculus Touch to the Vive controller. So would it be possible to just daisy chain things in some way?

**Comment by AndersMalmgren** [comment]
Freepie can emulate Hydra but it can not yet read oculus touch.

**Comment by thedonquixotic** [comment]
Cool, thanks @AndersMalmgren ! And thank you for starting this project!

**Comment by AndersMalmgren** [comment]
You could also try the mtbs3d forum, maybe someone with more time at their hands can help you implement this, or check reddit
