### ISSUE TITLE
sending data from FreePIE to opentrack

### ISSUE THREAD

**Issue by MigLeader** [AndersMalmgren/FreePIE#91]
hello everyone , just wanted to ask if its possible:

i was able to use trackir camera to get the values to FreePIE , what i want now is how i can export these values to opentrack , i am using the following code(i took it from the internet , its not mine):

```
def update():
    yaw = trackIR.yaw
    pitch = trackIR.pitch
    roll = trackIR.roll
    x = trackIR.x
    y = trackIR.y
    z = trackIR.z

if starting:
    trackIR.update += update
    
diagnostics.watch(trackIR.yaw)
diagnostics.watch(trackIR.pitch)
diagnostics.watch(trackIR.roll)
diagnostics.watch(trackIR.x)
diagnostics.watch(trackIR.y)
diagnostics.watch(trackIR.z)
```

so its simple , but sadly i am not a programmer at all , all i want is to use trackir 5 camera to use it inside riftcat as a positional tracking method.

thanks and i hope i am not doing anything wrong by asking here this question.

**Comment by zelmon64** [comment]
Firstly this would have been better asked on [mtbs3d](http://www.mtbs3d.com/phpBB/viewforum.php?f=139) especially as you would then have seem [this recent post](http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=22080&p=161925&sid=330e93c4df0ffd62916a78a81e3827aa#p161925) where CyberVillain discused why it's bad to do `diagnostics.watch(trackIR.roll)`.

Secondly you don't wan to output to opentrack but instead directly to FreeTrack (opentrack outputs to FreeTrack and that is what RiftCat VRidge reads.). Simply `freeTrack.x = trackIR.x` and similar will do what you want.

**Comment by MigLeader** [comment]
Firstly i am so sorry then for posting here , but i did post on mtbs3d but didnt get a respond , again so sorry.

Secondly, i guess i was so stupid that i didn't try what you said before , you sir just saved my time , thank you so much good sir , have a great day.

**Comment by zelmon64** [comment]
Sorry I couldn't understand what your goal was from your mtbs3d post when you said you changed freeTrack to openTrack (and I didn't know you are MigMan).

Glad it works now. Don't forget to close this issue.
